---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployApplication
spec:
  selector:
    matchLabels:
      app: blogwebapp
  replicas: 2
  template:
    metadata:
      labels:
        app: blogwebapp
    spec:
      containers:
      - name: blogwebapp
        image: saurabhbhai/project2
        ports:
        - name: http
          containerPort: 5000
