---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: bloggingApp
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  selector:
    matchLabels:
      app: bloggingApp
  replicas: 1
  template:
    metadata:
      labels:
        app: bloggingApp
    spec:
      containers:
      - name: bloggingApp
        image: saurabhbhai/project2
        ports:
        - containers: 5000
         
